name: MLOps Training Pipeline
on: [push]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    # Sécurité : On arrête le job s'il dépasse 15 minutes (évite de consommer tes quotas)
    timeout-minutes: 15 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execution du Pipeline MLRun
      # On force le mode local ici pour ignorer toute tentative de connexion réseau
      env:
         MLRUN_DBPATH: "local"
         MLRUN_ARTIFACT_PATH: "./artifac
      run: |
        python pipeline/pipeline.py

    - name: Sauvegarder les artefacts GitHub (Modèle et Graphes)
      if: always() # Sauvegarde même si une étape précédente a échoué (utile pour les logs)
      uses: actions/upload-artifact@v4
      with:
        name: agrisoil-ai-results
        # On sauvegarde tout le dossier artifacts (modèle .pkl, encodeurs et matrice de confusion)
        path: ./artifacts/
        retention-days: 5